const ExpensesActionTypes = {
	TOGGLE_ADD_EXPENSE: 'TOGGLE_ADD_EXPENSE',
	EDIT_NEW_EXPENSE: 'EDIT_NEW_EXPENSE',
	FETCH_EXPENSES_START: 'FETCH_EXPENSES_START',
	FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
	EXPENSES_FAILURE: 'EXPENSES_FAILURE',
	SET_TIME_FRAME: 'SET_TIME_FRAME',
	SET_DATE_RANGE: 'SET_DATE_RANGE',
	SET_CYCLE_DATE_RANGE: 'SET_CYCLE_DATE_RANGE',
	SET_SELECTED_EXPENSE: 'SET_SELECTED_EXPENSE',
	NEW_EXPENSE_START: 'NEW_EXPENSE_START',
	DELETE_EXPENSE_START: 'DELETE_EXPENSE_START'
}

export default ExpensesActionTypes;