const ExpensesActionTypes = {
	FETCH_EXPENSES_START: 'FETCH_EXPENSES_START',
	FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
	FETCH_EXPENSES_FAILURE: 'FETCH_EXPENSES_FAILURE'
}

export default ExpensesActionTypes;