const ExpensesActionTypes = {
	TOGGLE_ADD_EXPENSE: 'TOGGLE_ADD_EXPENSE',
	FETCH_EXPENSES_START: 'FETCH_EXPENSES_START',
	FETCH_EXPENSES_SUCCESS: 'FETCH_EXPENSES_SUCCESS',
	FETCH_EXPENSES_FAILURE: 'FETCH_EXPENSES_FAILURE',
	SET_TIME_FRAME: 'SET_TIME_FRAME',
	SET_DATE_RANGE: 'SET_DATE_RANGE',
	SET_CYCLE_DATE_RANGE: 'SET_CYCLE_DATE_RANGE',
	SET_SELECTED_EXPENSE: 'SET_SELECTED_EXPENSE',
	SET_EXPENSE_TO_EDIT: 'SET_EXPENSE_TO_EDIT'
}

export default ExpensesActionTypes;