const UserActionTypes = {
	EMAIL_SIGN_UP_START: 'EMAIL_SIGN_UP_START',
	SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',
	USER_FAILURE: 'USER_FAILURE',
	REGISTER_START: 'REGISTER_START',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	SIGN_IN_WITH_FACEBOOK_START: 'SIGN_IN_WITH_FACEBOOK_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	UPDATE_SETTINGS_START: 'UPDATE_SETTINGS_START',
	UPDATE_SETTINGS_SUCCESS: 'UPDATE_SETTINGS_SUCCESS',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	RESET_START: 'RESET_START'
} 

export default UserActionTypes;