const UserActionTypes = {
	EMAIL_SIGN_UP_START: 'EMAIL_SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	USER_FAILURE: 'USER_FAILURE',
	REGISTER_START: 'REGISTER_START',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	CHECK_USER_SESSION: 'CHECK_USER_SESSION',
	SET_USER_SETTINGS: 'SET_USER_SETTINGS',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS'
} 

export default UserActionTypes;